


//Items in Cart
let itemsToBuy =[];
let counter = 0;
let changeCounter = 0;

//Formatted items in cart for Stripe
let readyToBuy = [];

//All Products
const allProducts = [
  {
    'rec price 1': '10.5',
    'height (cm)': '6',
    'option 1': 'Forest Green',
    'rec price 4': '10.95',
    img: 'Images/products/Shopping Blocks/main.jpeg',
    'rec product 4': 'Hoop da Loops',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, geometric charms and earring studs and backs.',
    colour: 'dark green',
    'img 3': 'Images/products/Shopping Blocks/thumb3.jpeg',
    price: 'price_1HrhlpHqV6fz8FYoBYQAodm5',
    ID: 5,
    'img 1': 'Images/products/Shopping Blocks/thumb1.jpeg',
    'rec product 3': 'Penny Allsorts',
    quantity: 1,
    'rec price 2': '10.95',
    'rec product 1': 'Morning Paddles',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Red',
    'rec product 2': 'Tango Swirls',
    'img 2': 'Images/products/Shopping Blocks/thumb2.jpeg',
    'option 2': 'Mint',
    amount: 10.5,
    name: 'Shopping Blocks',
    'width (cm)': '2.5',
    'rec price 3': '9.95',
    freePrice: 'price_1HrhlpHqV6fz8FYoqSB6FGIb'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '6',
    'option 1': 'White',
    'rec price 4': '9.95',
    img: 'Images/products/Minty Ladies/main.jpeg',
    'rec product 4': 'Beach Pops',
    materials: 'Handmade from high-quality polymer clay with embossed fern print, connected with silver plated jump rings, circle charms and earring studs and backs.',
    colour: 'mint',
    'img 3': 'Images/products/Minty Ladies/thumb3.jpeg',
    price: 'price_1HrhmRHqV6fz8FYoSvGHjPcA',
    ID: 7,
    'img 1': 'Images/products/Minty Ladies/thumb1.jpeg',
    'rec product 3': 'Morning Paddles',
    quantity: 1,
    'rec price 2': '10.5',
    'rec product 1': 'Tango Swirls',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Curvy Girls',
    'img 2': 'Images/products/Minty Ladies/thumb2.jpeg',
    amount: 10.5,
    name: 'Minty Ladies',
    'width (cm)': '2.5',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhmRHqV6fz8FYo8KA3fGiO',
    'option 3': 'Mint'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '6.5',
    'option 1': 'White',
    'rec price 4': '10.5',
    img: 'Images/products/Penny Allsorts/main.jpeg',
    'rec product 4': 'Donuts',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, brass geometric charms and earring hooks.',
    colour: 'black',
    'img 3': 'Images/products/Penny Allsorts/thumb3.jpeg',
    price: 'price_1Hrhm8HqV6fz8FYoRHTDFqcc',
    ID: 9,
    'img 1': 'Images/products/Penny Allsorts/thumb1.jpeg',
    'rec product 3': 'Curvy Girls',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Shopping Blocks',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Mint',
    'rec product 2': 'Beach Pops',
    'img 2': 'Images/products/Penny Allsorts/thumb2.jpeg',
    'option 2': 'Red',
    amount: 9.95,
    name: 'Penny Allsorts',
    'width (cm)': '1.5',
    'rec price 3': '10.5',
    freePrice: 'price_1Hrhm8HqV6fz8FYovsETsYCO',
    'option 3': 'Black'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '7',
    'option 1': 'Pinkie',
    'rec price 4': '9.95',
    img: 'Images/products/Jelly Pinkies/main.jpeg',
    'rec product 4': 'Caterpillar Pops',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring hooks.',
    colour: 'pink',
    'img 3': 'Images/products/Jelly Pinkies/thumb3.jpeg',
    price: 'price_1Hrhm1HqV6fz8FYoEOUYFKyu',
    ID: 10,
    'img 1': 'Images/products/Jelly Pinkies/thumb1.jpeg',
    'rec product 3': 'Minty Ladies',
    quantity: 1,
    'rec price 2': '10.95',
    'rec product 1': 'Fish Bones',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Hoop da Loops',
    'img 2': 'Images/products/Jelly Pinkies/thumb2.jpeg',
    amount: 10.95,
    name: 'Jelly Pinkies',
    'width (cm)': '3.5',
    'rec price 3': '10.5',
    freePrice: 'price_1Hrhm1HqV6fz8FYoFlO6zw4t'
  },
  {
    'rec price 1': '9.95',
    'height (cm)': '9',
    'option 1': 'White',
    'rec price 4': '10.5',
    img: 'Images/products/Caterpillar Pops/main.jpeg',
    'rec product 4': 'Challahs',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring hooks.',
    colour: 'light green',
    'img 3': 'Images/products/Caterpillar Pops/thumb3.jpeg',
    'option 5': 'Lime Green',
    price: 'price_1HrhlNHqV6fz8FYoKp4t6epi',
    ID: 15,
    'img 1': 'Images/products/Caterpillar Pops/thumb1.jpeg',
    'rec product 3': 'Iced Donuts',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Beach Pops',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Forest Green',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Caterpillar Pops/thumb2.jpeg',
    'option 2': 'Tango',
    amount: 9.95,
    name: 'Caterpillar Pops',
    'width (cm)': '1.5',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhlNHqV6fz8FYoVm7Cb76O',
    'option 3': 'Red'
  },
  {
    'rec price 1': '12.95',
    'height (cm)': '7.3',
    'option 1': 'Black',
    'rec price 4': '14.95',
    img: 'Images/products/Sister Shellies/main.jpeg',
    'rec product 4': 'Cousins Curve',
    materials: 'Handmade from high-quality polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, decorative shell charm and earring hooks.',
    colour: 'Black',
    'img 3': 'Images/products/Sister Shellies/thumb3.jpeg',
    price: 'price_1HyxqmHqV6fz8FYoiLfbCqF6',
    ID: 17,
    'img 1': 'Images/products/Sister Shellies/thumb1.jpeg',
    'rec product 3': 'Cleopatras',
    quantity: 1,
    'rec price 2': '21.95',
    'rec product 1': 'Aunty Pearls',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Marble Set In Black',
    'img 2': 'Images/products/Sister Shellies/thumb2.jpeg',
    'option 2': 'Pearl',
    amount: 13.95,
    name: 'Sister Shellies',
    'width (cm)': '3.5',
    'rec price 3': '13.95',
    freePrice: 'price_1HyxqmHqV6fz8FYoLRhrkAEA'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '6',
    'option 1': 'Latte',
    'rec price 4': '10.95',
    img: 'Images/products/Curvy Girls/main.jpeg',
    'rec product 4': 'Fish Bones',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, circle charms and earring studs and backs.',
    colour: 'beige',
    'img 3': 'Images/products/Curvy Girls/thumb3.jpeg',
    price: 'price_1HrhlSHqV6fz8FYoNO9JPzam',
    ID: 12,
    'img 1': 'Images/products/Curvy Girls/thumb1.jpeg',
    'rec product 3': 'Challahs',
    quantity: 1,
    'rec price 2': '10.5',
    'rec product 1': 'Minty Ladies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Tango',
    'rec product 2': 'N-Dots',
    'img 2': 'Images/products/Curvy Girls/thumb2.jpeg',
    'option 2': 'White',
    amount: 10.5,
    name: 'Curvy Girls',
    'width (cm)': '2.5',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhlRHqV6fz8FYoOLvcAIJP'
  },
  {
    'rec price 1': '8.50',
    'height (cm)': '53.3',
    'option 1': 'Black',
    'rec price 4': '13.5',
    img: 'Images/products/Cousins Curve/main.jpeg',
    'rec product 4': 'Mother Moons',
    materials: 'Handmade from high-quality polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, chain and clasp.',
    colour: 'Black',
    'img 3': 'Images/products/Cousins Curve/thumb3.jpeg',
    price: 'price_1Hyxt1HqV6fz8FYoovZ0Hc67',
    ID: 22,
    'img 1': 'Images/products/Cousins Curve/thumb1.jpeg',
    'rec product 3': 'Marble Set In Pearl',
    quantity: 1,
    'rec price 2': '13.5',
    'rec product 1': 'Marbles',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Granny Gardens',
    'img 2': 'Images/products/Cousins Curve/thumb2.jpeg',
    'option 2': 'Pearl',
    amount: 14.95,
    name: 'Cousins Curve',
    'width (cm)': '2',
    'rec price 3': '21.95',
    freePrice: 'price_1Hyxt1HqV6fz8FYoSalXxArv'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '7',
    'option 1': 'Black',
    'rec price 4': '10.5',
    img: 'Images/products/Hoop da Loops/main.jpeg',
    'rec product 4': 'Curvy Girls',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, circle charms and earring hooks.',
    colour: 'blue',
    'img 3': 'Images/products/Hoop da Loops/thumb3.jpeg',
    price: 'price_1Hrhl0HqV6fz8FYorisFCu4J',
    ID: 2,
    'img 1': 'Images/products/Hoop da Loops/thumb1.jpeg',
    'rec product 3': 'Fish Bones',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Hoop da Loops/thumb2.jpeg',
    'option 2': 'Teal',
    amount: 10.95,
    name: 'Hoop da Loops',
    'width (cm)': '3.5',
    'rec price 3': '10.95',
    freePrice: 'price_1Hrhl0HqV6fz8FYoJitbIm3i',
    'option 3': 'Mint'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '6.5',
    'option 1': 'Tango',
    'rec price 4': '10.5',
    img: 'Images/products/Tango Swirls/main.jpeg',
    'rec product 4': 'Shopping Blocks',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, oval swilrs and earring hooks.',
    colour: 'orange',
    'img 3': 'Images/products/Tango Swirls/thumb3.jpeg',
    price: 'price_1HrhmWHqV6fz8FYooTf0oKnG',
    ID: 1,
    'img 1': 'Images/products/Tango Swirls/thumb1.jpeg',
    'rec product 3': 'Jelly Pinkies',
    quantity: 1,
    'rec price 2': '10.5',
    'rec product 1': 'N-Dots',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Minty Ladies',
    'img 2': 'Images/products/Tango Swirls/thumb2.jpeg',
    'option 2': 'White',
    amount: 10.95,
    name: 'Tango Swirls ',
    'width (cm)': '3',
    'rec price 3': '10.95',
    freePrice: 'price_1HrhmWHqV6fz8FYomvjsuBa9',
    'option 3': 'Black'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '4',
    'option 1': 'Teal',
    'rec price 4': '9.95',
    img: 'Images/products/Donuts/main.jpeg',
    'rec product 4': 'Beach Pops',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated posts and earring backs. ',
    colour: 'beige',
    'img 3': 'Images/products/Donuts/thumb3.jpeg',
    price: 'price_1HrhmbHqV6fz8FYoT76ckcep',
    ID: 3,
    'img 1': 'Images/products/Donuts/thumb1.jpeg',
    'rec product 3': 'Hoop da Loops',
    quantity: 1,
    'rec price 2': '10.5',
    'rec product 1': 'Iced Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Latte',
    'rec product 2': 'Challahs',
    'img 2': 'Images/products/Donuts/thumb2.jpeg',
    'option 2': 'Black',
    amount: 10.5,
    name: 'Donuts',
    'width (cm)': '4',
    'rec price 3': '10.95',
    freePrice: 'price_1HrhmbHqV6fz8FYo5XYlZpPw',
    'option 3': 'White'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '4',
    'option 1': 'Lime Green w/ White & Teal',
    'rec price 4': '10.5',
    img: 'Images/products/Iced Donuts/main.jpeg',
    'rec product 4': 'N-Dots',
    materials: 'Handmade from high-quality polymer clay with coloured print, connected with gold plated posts and earring backs. ',
    colour: 'beige',
    'img 3': 'Images/products/Iced Donuts/thumb3.jpeg',
    'option 5': 'Latte w/ Black & White',
    price: 'price_1Hrhk3HqV6fz8FYobbvajU66',
    ID: 14,
    'img 1': 'Images/products/Iced Donuts/thumb1.jpeg',
    'rec product 3': 'Hoop da Loops',
    quantity: 1,
    'rec price 2': '10.5',
    'rec product 1': 'Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'White w/ Grey & Black',
    'rec product 2': 'Challahs',
    'img 2': 'Images/products/Iced Donuts/thumb2.jpeg',
    'option 2': 'Forest Green w/ White & Mint',
    amount: 10.5,
    name: 'Iced Donuts',
    'width (cm)': '4',
    'rec price 3': '10.95',
    freePrice: 'price_1Hrhk3HqV6fz8FYo2Zvp3zFq',
    'option 3': 'Light Blue w/ White & Dark Blue'
  },
  {
    'rec price 1': '13.95',
    'height (cm)': '6',
    'option 1': 'Black',
    'rec price 4': '21.95',
    img: 'Images/products/Granny Gardens/main.jpeg',
    'rec product 4': 'Marble Set in Pearl',
    materials: 'Handmade from high-quality polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, decorative floral charm and earring hooks.',
    colour: 'Black',
    'img 3': 'Images/products/Granny Gardens/thumb3.jpeg',
    price: 'price_1HyxsDHqV6fz8FYojz9ELyHg',
    ID: 20,
    'img 1': 'Images/products/Granny Gardens/thumb1.jpeg',
    'rec product 3': 'Sister Shellies',
    quantity: 1,
    'rec price 2': '13.5',
    'rec product 1': 'Cleopatras',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Mother Moons',
    'img 2': 'Images/products/Granny Gardens/thumb2.jpeg',
    'option 2': 'Pearl',
    amount: 13.5,
    name: 'Granny Gardens',
    'width (cm)': '4',
    'rec price 3': '13.95',
    freePrice: 'price_1HyxsDHqV6fz8FYoQqe7Twfq'
  },
  {
    'rec price 1': '13.5',
    'height (cm)': '6.2',
    'option 1': 'Black',
    'rec price 4': '21.95',
    img: 'Images/products/Cleopatras/main.jpeg',
    'rec product 4': 'Marble Set in Black',
    materials: 'Handmade from high-quality black polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, decorative triangular charm and earring studs and backs.',
    colour: 'Black',
    'img 3': 'Images/products/Cleopatras/thumb3.jpeg',
    price: 'price_1HyxrjHqV6fz8FYokJBsP6sG',
    ID: 19,
    'img 1': 'Images/products/Cleopatras/thumb1.jpeg',
    'rec product 3': 'Aunty Pearls',
    quantity: 1,
    'rec price 2': '13.95',
    'rec product 1': 'Mother Moons',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Sister Shellies',
    'img 2': 'Images/products/Cleopatras/thumb2.jpeg',
    amount: 13.95,
    name: 'Cleopatras',
    'width (cm)': '3.5',
    'rec price 3': '12.95',
    freePrice: 'price_1HyxrjHqV6fz8FYo8X6Y7Zpc'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '4',
    'option 1': 'Black',
    'rec price 4': '10.95',
    img: 'Images/products/Morning Paddles/main.jpeg',
    'rec product 4': 'Jelly Pinkies',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, semi-circle charms and earring studs and backs.',
    colour: 'mint',
    'img 3': 'Images/products/Morning Paddles/thumb3.jpeg',
    price: 'price_1HrhmEHqV6fz8FYo1bBTM9nj',
    ID: 8,
    'img 1': 'Images/products/Morning Paddles/thumb1.jpeg',
    'rec product 3': 'Shopping Blocks',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Hoop da Loops',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Morning Paddles/thumb2.jpeg',
    'option 2': 'Teal',
    amount: 10.5,
    name: 'Morning Paddles',
    'width (cm)': '3.5',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhmEHqV6fz8FYoTyFsu4yY',
    'option 3': 'Mint'
  },
  {
    'rec price 1': '14.95',
    'height (cm)': '5.7',
    'option 1': 'Black',
    'rec price 4': '8.50',
    img: 'Images/products/Aunty Pearls/main.jpeg',
    'rec product 4': 'Marbles',
    materials: 'Handmade from high-quality polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, decorative pearls and earring studs and backs.',
    colour: 'Black',
    'img 3': 'Images/products/Aunty Pearls/thumb3.jpeg',
    price: 'price_1Hz6WDHqV6fz8FYoxYliKlF9',
    ID: 16,
    'img 1': 'Images/products/Aunty Pearls/thumb1.jpeg',
    'rec product 3': 'Granny Gardens',
    quantity: 1,
    'rec price 2': '21.95',
    'rec product 1': 'Cousins Curve',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Marble Set In Pearl',
    'img 2': 'Images/products/Aunty Pearls/thumb2.jpeg',
    'option 2': 'Pearl',
    amount: 12.95,
    name: 'Aunty Pearls',
    'width (cm)': '1.2',
    'rec price 3': '13.5',
    freePrice: 'price_1Hz6WDHqV6fz8FYok0EULw0H'
  },
  {
    'rec price 1': '13.95',
    'height (cm)': '5',
    'option 1': 'Black',
    'rec price 4': '13.5',
    img: 'Images/products/Mother Moons/main.jpeg',
    'rec product 4': 'Granny Gardens',
    materials: 'Handmade from high-quality polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, earring studs and backs and decorative brass semi circle and square charms.',
    colour: 'Black',
    'img 3': 'Images/products/Mother Moons/thumb3.jpeg',
    price: 'price_1Hyxr8HqV6fz8FYouGFsL0Gm',
    ID: 18,
    'img 1': 'Images/products/Mother Moons/thumb1.jpeg',
    'rec product 3': 'Marble Set In Black',
    quantity: 1,
    'rec price 2': '12.95',
    'rec product 1': 'Sister Shellies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Aunty Pearls',
    'img 2': 'Images/products/Mother Moons/thumb2.jpeg',
    'option 2': 'Pearl',
    amount: 13.5,
    name: 'Mother Moons',
    'width (cm)': '4',
    'rec price 3': '21.95',
    freePrice: 'price_1Hyxr8HqV6fz8FYoTG66zdEc'
  },
  {
    'rec price 1': '13.5',
    'height (cm)': '1.2',
    'option 1': 'Black',
    'rec price 4': '13.95',
    img: 'Images/products/Marbles/main.jpeg',
    'rec product 4': 'Sister Shellies',
    materials: 'Handmade from high-quality polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated earring posts and backs.',
    colour: 'Black',
    'img 3': 'Images/products/Marbles/thumb3.jpeg',
    price: 'price_1HyxscHqV6fz8FYoiT91JKsn',
    ID: 21,
    'img 1': 'Images/products/Marbles/thumb1.jpeg',
    'rec product 3': 'Mother Moons',
    quantity: 1,
    'rec price 2': '13.95',
    'rec product 1': 'Granny Gardens',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Cleopatras',
    'img 2': 'Images/products/Marbles/thumb2.jpeg',
    'option 2': 'Pearl',
    amount: 8.5,
    name: 'Marbles',
    'width (cm)': '1.2',
    'rec price 3': '13.5',
    freePrice: 'price_1HyxscHqV6fz8FYoTOmNfPB1'
  },
  {
    'rec price 1': '9.95',
    'height (cm)': '9',
    'option 1': 'Beige w/ Black',
    'rec price 4': '10.5',
    img: 'Images/products/Beach Pops/main.jpeg',
    'rec product 4': 'Challahs',
    materials: 'Handmade from high-quality polymer clay with a marbled effect, connected with gold or silver plated jump rings and earring studs and backs.',
    colour: 'beige',
    'img 3': 'Images/products/Beach Pops/thumb3.jpeg',
    price: 'price_1HrhlJHqV6fz8FYo3dVkbLvK',
    ID: 11,
    'img 1': 'Images/products/Beach Pops/thumb1.jpeg',
    'rec product 3': 'Tango Swirls',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Caterpillar Pops',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Blue w/ White',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Beach Pops/thumb2.jpeg',
    'option 2': 'Black w/ White',
    amount: 9.95,
    name: 'Beach Pops',
    'width (cm)': '1.5',
    'rec price 3': '10.95',
    freePrice: 'price_1HrhlJHqV6fz8FYopi1gSHyi'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '5',
    'option 1': 'White',
    'rec price 4': '10.95',
    img: 'Images/products/N-Dots/main.jpeg',
    'rec product 4': 'Fish Bones',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring studs and backs.',
    colour: 'black',
    'img 3': 'Images/products/N-Dots/thumb3.jpeg',
    'option 5': 'Black',
    price: 'price_1HrhmKHqV6fz8FYozUf4EuqP',
    ID: 6,
    'img 1': 'Images/products/N-Dots/thumb1.jpeg',
    'rec product 3': 'Curvy Girls',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Minty Ladies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Black Marbled',
    'rec product 2': 'Caterpillar Pops',
    'img 2': 'Images/products/N-Dots/thumb2.jpeg',
    'option 2': 'Red Marbled',
    amount: 10.5,
    name: 'N-Dots',
    'width (cm)': '2.5',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhmKHqV6fz8FYoFOzePptr',
    'option 3': 'Red'
  },
  {
    'rec price 1': '21.95',
    'height (cm)': '1/53.5',
    'option 1': 'Black',
    'rec price 4': '12.95',
    img: 'Images/products/Collection In Black/main.jpeg',
    'rec product 4': 'Aunty Pearls',
    materials: 'Necklace: Handmade from high-quality black polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, chain and clasp.\n' +
      'Studs: Handmade from high-quality black polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated earring posts and backs.',
    colour: 'Black',
    'img 3': 'Images/products/Collection In Black/thumb3.jpeg',
    price: 'price_1HyxtkHqV6fz8FYoyJz0dT11',
    ID: 24,
    'img 1': 'Images/products/Collection In Black/thumb1.jpeg',
    'rec product 3': 'Cousins Curve',
    quantity: 1,
    'rec price 2': '8.50',
    'rec product 1': 'Marble Set In Pearl',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Marbles',
    'img 2': 'Images/products/Collection In Black/thumb2.jpeg',
    amount: 21.95,
    name: 'Marble Set In Black',
    'width (cm)': ' 1/2',
    'rec price 3': '14.95',
    freePrice: 'price_1HyxtkHqV6fz8FYoUHVYau8N'
  },
  {
    'rec price 1': '21.95',
    'height (cm)': '1/53.5',
    'option 1': 'Pearl',
    'rec price 4': '13.95',
    img: 'Images/products/Collection In White/main.jpeg',
    'rec product 4': 'Cleopatras',
    materials: 'Necklace: Handmade from high-quality translucent polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated jump rings, chain and clasp.\n' +
      'Studs: Handmade from high-quality translucent polymer clay with Mica powder and alcohol inks for a marble effect, connected with gold plated earring posts and backs.',
    colour: 'Black',
    'img 3': 'Images/products/Collection In White/thumb3.jpeg',
    price: 'price_1HyxtQHqV6fz8FYo5V1SlacX',
    ID: 23,
    'img 1': 'Images/products/Collection In White/thumb1.jpeg',
    'rec product 3': 'Marbles',
    quantity: 1,
    'rec price 2': '14.95',
    'rec product 1': 'Marble Set In Black',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Cousins Curve',
    'img 2': 'Images/products/Collection In White/thumb2.jpeg',
    amount: 21.95,
    name: 'Marble Set In Pearl',
    'width (cm)': ' 1/2',
    'rec price 3': '8.50',
    freePrice: 'price_1HyxtQHqV6fz8FYoZ61yOb1S'
  },
  {
    'rec price 1': '10.5',
    'height (cm)': '3',
    'option 1': 'White',
    'rec price 4': '10.5',
    img: 'Images/products/Challahs/main.jpeg',
    'rec product 4': 'N-Dots',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated posts and earring backs. ',
    colour: 'beige',
    'img 3': 'Images/products/Challahs/thumb3.jpeg',
    price: 'price_1HrhlDHqV6fz8FYoGNPnlPM5',
    ID: 4,
    'img 1': 'Images/products/Challahs/thumb1.jpeg',
    'rec product 3': 'Iced Donuts',
    quantity: 1,
    'rec price 2': '10.5',
    'rec product 1': 'Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Curvy Girls',
    'img 2': 'Images/products/Challahs/thumb2.jpeg',
    'option 2': 'Black',
    amount: 10.5,
    name: 'Challahs',
    'width (cm)': '3',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhlDHqV6fz8FYoMklTsGoV',
    'option 3': 'Latte'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '7.5',
    'option 1': 'Tango',
    'rec price 4': '10.5',
    img: 'Images/products/Fish Bones/main.jpeg',
    'rec product 4': 'Curvy Girls',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring hooks.',
    colour: 'orange',
    'img 3': 'Images/products/Fish Bones/thumb3.jpeg',
    price: 'price_1HrhljHqV6fz8FYo7PoyO4Zp',
    ID: 13,
    'img 1': 'Images/products/Fish Bones/thumb1.jpeg',
    'rec product 3': 'Donuts',
    quantity: 1,
    'rec price 2': '10.95',
    'rec product 1': 'Jelly Pinkies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Hoop da Loops',
    'img 2': 'Images/products/Fish Bones/thumb2.jpeg',
    amount: 10.95,
    name: 'Fish Bones',
    'width (cm)': '3.5',
    'rec price 3': '10.5',
    freePrice: 'price_1HrhljHqV6fz8FYoqxxqRgTM'
  }
]