


//Items in Cart
let itemsToBuy =[];
let counter = 0;
let changeCounter = 0;

//Formatted items in cart for Stripe
let readyToBuy = [];

//All Products
const allProducts = [
  {
    'rec price 1': '10.50',
    'height (cm)': '5',
    'option 1': 'White',
    'rec price 4': '10.95',
    img: 'Images/products/N-Dots/main.jpeg',
    'rec product 4': 'Fish Bones',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring posts.',
    colour: 'black',
    'img 3': 'Images/products/N-Dots/thumb3.jpeg',
    'option 5': 'Black',
    price: 'price_1HpMDGHqV6fz8FYovTB7BExt',
    ID: 7,
    'img 1': 'Images/products/N-Dots/thumb1.jpeg',
    'rec product 3': 'Curvy Girls',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Minty Ladies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Black Marbled',
    'rec product 2': 'Caterpillar Pops',
    'img 2': 'Images/products/N-Dots/thumb2.jpeg',
    'option 2': 'Red Marbled',
    amount: 10.5,
    name: 'N-Dots',
    'width (cm)': '2.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HqGY6HqV6fz8FYo7RtNkbpu',
    'option 3': 'Red'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '4',
    'option 1': 'Black',
    'rec price 4': '10.95',
    img: 'Images/products/Morning Paddles/main.jpeg',
    'rec product 4': 'Jelly Pinkies',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, semi-circle charms and earring posts.',
    colour: 'mint',
    'img 3': 'Images/products/Morning Paddles/thumb3.jpeg',
    price: 'price_1HpMFYHqV6fz8FYoEE1faKz1',
    ID: 9,
    'img 1': 'Images/products/Morning Paddles/thumb1.jpeg',
    'rec product 3': 'Shopping Blocks',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Hoop da Loops',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Morning Paddles/thumb2.jpeg',
    'option 2': 'Blue',
    amount: 10.5,
    name: 'Morning Paddles',
    'width (cm)': '3.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HqGXHHqV6fz8FYo7YiJ6t41',
    'option 3': 'Mint'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '7',
    'option 1': 'Pink',
    'rec price 4': '9.95',
    img: 'Images/products/Jelly Pinkies/main.jpeg',
    'rec product 4': 'Caterpillar Pops',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring hooks.',
    colour: 'pink',
    'img 3': 'Images/products/Jelly Pinkies/thumb3.jpeg',
    price: 'price_1HpMImHqV6fz8FYoHuLHYbmf',
    ID: 11,
    'img 1': 'Images/products/Jelly Pinkies/thumb1.jpeg',
    'rec product 3': 'Minty Ladies',
    quantity: 1,
    'rec price 2': '10.95',
    'rec product 1': 'Fish Bones',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Hoop da Loops',
    'img 2': 'Images/products/Jelly Pinkies/thumb2.jpeg',
    amount: 10.95,
    name: 'Jelly Pinkies',
    'width (cm)': '3.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HqGTfHqV6fz8FYos1o8Uisc'
  },
  {
    'rec price 1': '9.95',
    'height (cm)': '9',
    'option 1': 'Beige w/ Black',
    'rec price 4': '10.50',
    img: 'Images/products/Beach Pops/main.jpeg',
    'rec product 4': 'Challahs',
    materials: 'Handmade from high-quality polymer clay with a marbled effect, connected with gold or silver plated jump rings and earring posts.',
    colour: 'beige',
    'img 3': 'Images/products/Beach Pops/thumb3.jpeg',
    price: 'price_1Hr1DHHqV6fz8FYor1cSh2x2',
    ID: 12,
    'img 1': 'Images/products/Beach Pops/thumb1.jpeg',
    'rec product 3': 'Tango Swirls',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Caterpillar Pops',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Beach Pops/thumb2.jpeg',
    'option 2': 'Black w/ White',
    amount: 9.95,
    name: 'Beach Pops',
    'width (cm)': '1.5',
    'rec price 3': '10.95',
    freePrice: 'price_1Hr1DHHqV6fz8FYobM9dOkli',
    'option 4': 'Blue w/ White'
  },
  { ID: 22, quantity: 1, img: 'Images/ear.png' },
  {
    'rec price 1': '10.95',
    'height (cm)': '7.5',
    'option 1': 'Orange',
    'rec price 4': '10.50',
    img: 'Images/products/Fish Bones/main.jpeg',
    'rec product 4': 'Curvy Girls',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring hooks.',
    colour: 'orange',
    'img 3': 'Images/products/Fish Bones/thumb3.jpeg',
    price: 'price_1HpMMGHqV6fz8FYoklYRhc6H',
    ID: 17,
    'img 1': 'Images/products/Fish Bones/thumb1.jpeg',
    'rec product 3': 'Donuts',
    quantity: 1,
    'rec price 2': '10.95',
    'rec product 1': 'Jelly Pinkies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Hoop da Loops',
    'img 2': 'Images/products/Fish Bones/thumb2.jpeg',
    amount: 10.95,
    name: 'Fish Bones',
    'width (cm)': '3.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HqGRkHqV6fz8FYoO9HEXR8A'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '4',
    'option 1': 'Blue',
    'rec price 4': '9.95',
    img: 'Images/products/Donuts/main.jpeg',
    'rec product 4': 'Beach Pops',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated posts and earring backs. ',
    colour: 'beige',
    'img 3': 'Images/products/Donuts/thumb3.jpeg',
    price: 'price_1HpKxzHqV6fz8FYoUWFgPjQT',
    ID: 3,
    'img 1': 'Images/products/Donuts/thumb1.jpeg',
    'rec product 3': 'Hoop da Loops',
    quantity: 1,
    'rec price 2': '10.50',
    'rec product 1': 'Iced Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Latte',
    'rec product 2': 'Challahs',
    'img 2': 'Images/products/Donuts/thumb2.jpeg',
    'option 2': 'Black',
    amount: 10.5,
    name: 'Donuts',
    'width (cm)': '4',
    'rec price 3': '10.95',
    freePrice: 'price_1HphCGHqV6fz8FYoVtnLqerr',
    'option 3': 'White'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '7',
    'option 1': 'Black',
    'rec price 4': '10.50',
    img: 'Images/products/Hoop da Loops/main.jpeg',
    'rec product 4': 'Curvy Girls',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, circle charms and earring hooks.',
    colour: 'blue',
    'img 3': 'Images/products/Hoop da Loops/thumb3.jpeg',
    price: 'price_1Hr1QvHqV6fz8FYoiHzjnwl4',
    ID: 2,
    'img 1': 'Images/products/Hoop da Loops/thumb1.jpeg',
    'rec product 3': 'Fish Bones',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Hoop da Loops/thumb2.jpeg',
    'option 2': 'Blue',
    amount: 10.95,
    name: 'Hoop da Loops',
    'width (cm)': '3.5',
    'rec price 3': '10.95',
    freePrice: 'price_1Hr1QwHqV6fz8FYouhWudJJ4',
    'option 3': 'Mint'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '3',
    'option 1': 'Beige',
    'rec price 4': '10.50',
    img: 'Images/products/Challahs/main.jpeg',
    'rec product 4': 'N-Dots',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated posts and earring backs. ',
    colour: 'beige',
    'img 3': 'Images/products/Challahs/thumb3.jpeg',
    price: 'price_1Hr1EJHqV6fz8FYoUDAtl5Ay',
    ID: 5,
    'img 1': 'Images/products/Challahs/thumb1.jpeg',
    'rec product 3': 'Iced Donuts',
    quantity: 1,
    'rec price 2': '10.50',
    'rec product 1': 'Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Latte',
    'rec product 2': 'Curvy Girls',
    'img 2': 'Images/products/Challahs/thumb2.jpeg',
    'option 2': 'White',
    amount: 10.5,
    name: 'Challahs',
    'width (cm)': '3',
    'rec price 3': '10.50',
    freePrice: 'price_1Hr1EKHqV6fz8FYokl8zZngw',
    'option 3': 'Black'
  },
  {
    'rec price 1': '9.95',
    'height (cm)': '9',
    'option 1': 'White',
    'rec price 4': '10.50',
    img: 'Images/products/Caterpillar Pops/main.jpeg',
    'rec product 4': 'Challahs',
    materials: 'Handmade from high-quality polymer clay, connected with gold or silver plated jump rings and earring posts.',
    colour: 'light green',
    'img 3': 'Images/products/Caterpillar Pops/thumb3.jpeg',
    price: 'price_1HpMT1HqV6fz8FYovGzKorpK',
    ID: 19,
    'img 1': 'Images/products/Caterpillar Pops/thumb1.jpeg',
    'rec product 3': 'Iced Donuts',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Beach Pops',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Dark Green',
    'rec product 2': 'Penny Allsorts',
    'img 2': 'Images/products/Caterpillar Pops/thumb2.jpeg',
    'option 2': 'Orange',
    amount: 9.95,
    name: 'Caterpillar Pops',
    'width (cm)': '1.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HpMQ8HqV6fz8FYoVE8r38RB',
    'option 3': 'Red',
    'option 5': 'Lime Green'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '6.5',
    'option 1': 'White',
    'rec price 4': '10.50',
    img: 'Images/products/Penny Allsorts/main.jpeg',
    'rec product 4': 'Donuts',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, brass geometric charms and earring hooks.',
    colour: 'black',
    'img 3': 'Images/products/Penny Allsorts/thumb3.jpeg',
    price: 'price_1HpMGwHqV6fz8FYojbHc5mkj',
    ID: 10,
    'img 1': 'Images/products/Penny Allsorts/thumb1.jpeg',
    'rec product 3': 'Curvy Girls',
    quantity: 1,
    'rec price 2': '9.95',
    'rec product 1': 'Shopping Blocks',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'Mint',
    'rec product 2': 'Beach Pops',
    'img 2': 'Images/products/Penny Allsorts/thumb2.jpeg',
    'option 2': 'Red',
    amount: 9.95,
    name: 'Penny Allsorts',
    'width (cm)': '1.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HqGUpHqV6fz8FYouIAzMJTE',
    'option 3': 'Black'
  },
  { ID: 21, quantity: 1, img: 'Images/ear.png' },
  {
    'rec price 1': '10.50',
    'height (cm)': '6',
    'option 1': 'Latte',
    'rec price 4': '10.95',
    img: 'Images/products/Curvy Girls/main.jpeg',
    'rec product 4': 'Fish Bones',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, circle charms and earring posts.',
    colour: 'beige',
    'img 3': 'Images/products/Curvy Girls/thumb3.jpeg',
    price: 'price_1HpMNwHqV6fz8FYoOlzWTta6',
    ID: 16,
    'img 1': 'Images/products/Curvy Girls/thumb1.jpeg',
    'rec product 3': 'Challahs',
    quantity: 1,
    'rec price 2': '10.50',
    'rec product 1': 'Minty Ladies',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'N-Dots',
    'img 2': 'Images/products/Curvy Girls/thumb2.jpeg',
    'option 2': 'White',
    amount: 10.5,
    name: 'Curvy Girls',
    'width (cm)': '2.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HqGP9HqV6fz8FYo0XvHwgph',
    'option 4': 'Orange'
  },
  {
    'rec price 1': '10.95',
    'height (cm)': '6',
    'option 1': 'White',
    'rec price 4': '9.95',
    img: 'Images/products/Minty Ladies/main.jpeg',
    'rec product 4': 'Beach Pops',
    materials: 'Handmade from high-quality polymer clay with embossed fern print, connected with silver plated jump rings, circle charms and earring posts.',
    colour: 'mint',
    'img 3': 'Images/products/Minty Ladies/thumb3.jpeg',
    price: 'price_1HpMAZHqV6fz8FYomNpxsMvj',
    ID: 8,
    'img 1': 'Images/products/Minty Ladies/thumb1.jpeg',
    'rec product 3': 'Morning Paddles',
    quantity: 1,
    'rec price 2': '10.50',
    'rec product 1': 'Tango Swirls',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Curvy Girls',
    'img 2': 'Images/products/Minty Ladies/thumb2.jpeg',
    amount: 10.5,
    name: 'Minty Ladies',
    'width (cm)': '2.5',
    'rec price 3': '10.50',
    freePrice: 'price_1HphBVHqV6fz8FYov4SX4hyO',
    'option 3': 'Mint'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '6',
    'option 1': 'Dark Green',
    'rec price 4': '10.95',
    img: 'Images/products/Shopping Blocks/main.jpeg',
    'rec product 4': 'Hoop da Loops',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, geometric charms and earring hooks.',
    colour: 'dark green',
    'img 3': 'Images/products/Shopping Blocks/thumb3.jpeg',
    price: 'price_1HpMJsHqV6fz8FYo9wmoFQ7w',
    ID: 6,
    'img 1': 'Images/products/Shopping Blocks/thumb1.jpeg',
    'rec product 3': 'Penny Allsorts',
    quantity: 1,
    'rec price 2': '10.95',
    'rec product 1': 'Morning Paddles',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Tango Swirls',
    'img 2': 'Images/products/Shopping Blocks/thumb2.jpeg',
    'option 2': 'Mint',
    amount: 10.5,
    name: 'Shopping Blocks',
    'width (cm)': '2.5',
    'rec price 3': '9.95',
    freePrice: 'price_1HqGTHHqV6fz8FYoONRwmCvD',
    'option 4': 'Red'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '4',
    'option 1': 'Lime Green w/ White & Green',
    'rec price 4': '10.50',
    img: 'Images/products/Iced Donuts/main.jpeg',
    'rec product 4': 'N-Dots',
    materials: 'Handmade from high-quality polymer clay with coloured print, connected with gold plated posts and earring backs. ',
    colour: 'beige',
    'img 3': 'Images/products/Iced Donuts/thumb3.jpeg',
    price: 'price_1Hr3JSHqV6fz8FYo00POO16T',
    ID: 18,
    'img 1': 'Images/products/Iced Donuts/thumb1.jpeg',
    'rec product 3': 'Hoop da Loops',
    quantity: 1,
    'rec price 2': '10.50',
    'rec product 1': 'Donuts',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'option 4': 'White w/ Grey & Black',
    'rec product 2': 'Challahs',
    'img 2': 'Images/products/Iced Donuts/thumb2.jpeg',
    'option 2': 'Blue w/ White & Mint',
    amount: 10.5,
    name: 'Iced Donuts',
    'width (cm)': '4',
    'rec price 3': '10.95',
    freePrice: 'price_1Hr3JSHqV6fz8FYokAt6eHSA',
    'option 3': 'Blue w/ White & Dark Blue',
    'option 5': 'Latte w/ Black & White'
  },
  {
    'rec price 1': '10.50',
    'height (cm)': '6.5',
    'option 1': 'Black',
    'rec price 4': '10.50',
    img: 'Images/products/Tango Swirls/main.jpeg',
    'rec product 4': 'Shopping Blocks',
    materials: 'Handmade from high-quality polymer clay, connected with gold plated jump rings, oval swilrs and earring hooks.',
    colour: 'orange',
    'img 3': 'Images/products/Tango Swirls/thumb3.jpeg',
    price: 'price_1HpM91HqV6fz8FYoOkPczDBB',
    ID: 1,
    'img 1': 'Images/products/Tango Swirls/thumb1.jpeg',
    'rec product 3': 'Jelly Pinkies',
    quantity: 1,
    'rec price 2': '10.50',
    'rec product 1': 'N-Dots',
    description: 'Each earring is one of a kind, so please allow for any slight variations or imperfections! Each piece is designed and made by me. I hand mix the clay to create original colours, roll, emboss, bake, sand, drill, glaze and assemble everything in my shop!',
    'rec product 2': 'Minty Ladies',
    'img 2': 'Images/products/Tango Swirls/thumb2.jpeg',
    'option 2': 'White',
    amount: 10.95,
    name: 'Tango Swirls',
    'width (cm)': '3',
    'rec price 3': '10.95',
    freePrice: 'price_1HphBtHqV6fz8FYoeOp8Norb',
    'option 3': 'Orange'
  }
]