import pandas as pd
from shutil import copyfile
import os
from openpyxl import load_workbook

data = pd.read_excel("/Users/milanvanniekerk/Desktop/MadeByB/admin/products.xlsx")
df = pd.DataFrame(data)

for index in df.index:
    ID = str(df['ID'][index])
    name = str(df['name'][index])
    price = str(df['price'][index])
    quantity = str(df['quantity'][index])
    img = str(df['img'][index])
    img1 = str(df['img 1'][index])
    img2 = str(df['img 2'][index])
    img3 = str(df['img 3'][index])
    amount = str(df['amount'][index])
    freePrice = str(df['freePrice'][index])
    colour = str(df['colour'][index])
    option1 = str(df['option 1'][index])
    option2 = str(df['option 2'][index])
    option3 = str(df['option 3'][index])
    option4 = str(df['option 4'][index])
    option5 = str(df['option 5'][index])
    option6 = str(df['option 6'][index])
    height = str(df['height (cm)'][index])
    width = str(df['width (cm)'][index])
    materials = str(df['materials'][index])
    description = str(df['description'][index])
    recProduct1 = str(df['rec product 1'][index])
    recPrice1 = str(df['rec price 1'][index])
    recProduct2 = str(df['rec product 2'][index])
    recPrice2 = str(df['rec price 2'][index])
    recProduct3 = str(df['rec product 3'][index])
    recPrice3 = str(df['rec price 3'][index])
    recProduct4 = str(df['rec product 4'][index])
    recPrice4 = str(df['rec price 4'][index])
   

    copyfile("/Users/milanvanniekerk/Desktop/MadeByB/products/template.html", "/Users/milanvanniekerk/Desktop/MadeByB/products/" + name + ".txt")

    fin = open("/Users/milanvanniekerk/Desktop/MadeByB/products/" + name + ".txt", "rt")
    data = fin.read()
    data = data.replace('#name', name)
    data = data.replace('#img', img)
    data = data.replace('#x', img1)
    data = data.replace('#y', img2)
    data = data.replace('#z', img3)
    data = data.replace('#amount', amount)
    data = data.replace('#option1', option1)
    data = data.replace('#option2', option2)
    data = data.replace('#option3', option3)
    data = data.replace('#option4', option4)
    data = data.replace('#option5', option5)
    data = data.replace('#option6', option6)
    data = data.replace('#height', height)
    data = data.replace('#width', width)
    data = data.replace('#materials', materials)
    data = data.replace('#description', description)
    data = data.replace('#rec product 1', recProduct1)
    data = data.replace('#rec product 1', recProduct1)
    data = data.replace('#rec product 1', recProduct1)
    data = data.replace('#rec price 1', recPrice1)
    data = data.replace('#rec product 2', recProduct2)
    data = data.replace('#rec product 2', recProduct2)
    data = data.replace('#rec product 2', recProduct2)
    data = data.replace('#rec price 2', recPrice2)
    data = data.replace('#rec product 3', recProduct3)
    data = data.replace('#rec product 3', recProduct3)
    data = data.replace('#rec product 3', recProduct3)
    data = data.replace('#rec price 3', recPrice3)
    data = data.replace('#rec product 4', recProduct4)
    data = data.replace('#rec product 4', recProduct4)
    data = data.replace('#rec product 4', recProduct4)
    data = data.replace('#rec price 4', recPrice4)

    fin.close()
    fin = open("/Users/milanvanniekerk/Desktop/MadeByB/products/" + name + ".txt", "wt")
    fin.write(data)
    fin.close()

    copyfile("/Users/milanvanniekerk/Desktop/MadeByB/products/" + name + ".txt","/Users/milanvanniekerk/Desktop/MadeByB/products/" + name + ".html")

    os.remove("/Users/milanvanniekerk/Desktop/MadeByB/products/" + name + ".txt")
